spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://42.192.153.6:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: luobo
    password: luobo
    min-idle: 50
    initial-size: 20
    max-total: 50
    max-wait-millis: 200
  redis:
    database: 0
    host: 42.192.153.6
    port: 6379
    password: 111111
    jedis:
      pool:
        max-active: 600
        max-wait: 8000
        max-idle: 300
        min-idle: 50
        max-wait-millis: 10000
    timeout: 10000
